//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FashionStore.AllTables
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CreamchicEntities : DbContext
    {
        public CreamchicEntities()
            : base("name=CreamchicEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CartStatusTbl> CartStatusTbls { get; set; }
        public virtual DbSet<CartTbl> CartTbls { get; set; }
        public virtual DbSet<CategoryTbl> CategoryTbls { get; set; }
        public virtual DbSet<MemberRoleTbl> MemberRoleTbls { get; set; }
        public virtual DbSet<MembersTbl> MembersTbls { get; set; }
        public virtual DbSet<ProductTbl> ProductTbls { get; set; }
        public virtual DbSet<RolesTbl> RolesTbls { get; set; }
        public virtual DbSet<ShippingDetailsTbl> ShippingDetailsTbls { get; set; }
        public virtual DbSet<SlideImageTbl> SlideImageTbls { get; set; }
    }
}
